### PR TITLE
Replaced svnversion with short git hack

### PR DESCRIPTION
**Pull request by e8johan**
Replaced svnversion with a hack that extracts the short hash using git log and then appends an M if there are modified files in the clone using git status.

### CODE REVIEW

**Comment by sreejithr** [comment]
Neat :+1:

**Comment by mattn** [comment]
Please use `$(shell)` for multi-platform.

```
VERSION+=$(shell git log --oneline -n 1 | sed 's/\ .*//')$(shell git status --porcelain | grep -q '^\ M' && echo -n M)
CC=gcc
CFLAGS=-Wall -pedantic -g -DUNIX_HOST -DVER=\"${VERSION}\"
LIBS=-lm -lreadline
```
This works on windows too.

**Comment by e8johan** [comment]
Cool. Then I'll close this one.

**Comment by mattn** [comment]
However, @zsaleeba seems not active for this repo.

**Comment by zsaleeba** [comment]
Sorry, I'll be back and active soon. I'm a bit snowed under with other stuff right now.

**Comment by e8johan** [comment]
Great to hear from you! Looking forward to moving this project ahead!

**Pull request closed without merging**
